data_name: "Musk"
fourier_orth_settings:
    max_depth: 3
    cluster_sizes: [166, 50, 31]
    selection_thresholds: [0.999,0.9995,0.999]
    norm_epsilon: [0.001, 0.001, 0.001]
    shuffle: False
    preranking: "non"
random_states: [42, 100, 0, 25, 80]
algorithms: [
  "UFFS + SFFS (t=3)", "UFFS + SFFS (t=2)", "UFFS + SFFS (t=1)", "CCM", "ReliefF", "mRMR", "MI", "RFS", "F-Value"
  ]

