data_name: "USPS"
fourier_orth_settings:
    max_depth: 3
    cluster_sizes: [-1, 40, 20]
    selection_thresholds: [0.95,0.98,0.999]
    norm_epsilon: [0.001, 0.001, 0.0001]
    shuffle: False
    preranking: "non"
random_states: [42, 100, 0, 25, 80]
algorithms: [
  "UFFS + SFFS (t=3)", "UFFS + SFFS (t=2)", "UFFS + SFFS (t=1)", "ReliefF", "mRMR", "MI", "RFS"]

